### ISSUE TITLE
High latency with multiple URLs

### ISSUE THREAD

**Issue by edent** [embedkit/php-example#1]
Running a query with multiple URLs results in a very high latency.

This extract request took ~7 seconds to complete

    https://embedkit.com/api/v1/extract?key=s_1234&urls=http%3A%2F%2Ftmblr.co%2FZRYINw1aCekCD,http%3A%2F%2FDIYBinge.com,http%3A%2F%2Ftinyurl.com%2Fn649nk5,http%3A%2F%2Ffw.to%2FEuO9b0W,http%3A%2F%2Fbit.ly%2F1xLJzsO,http%3A%2F%2Fpublicstrategist.com%2F2015%2F01%2Fnuclear-catastrophes-speeding-tickets-and-agility%2F,http%3A%2F%2Fdlvr.it%2F83MnnM,http%3A%2F%2Fnews.sky.com%2Fstory%2F1404574%2Ftributes-to-muslim-officer-killed-by-terrorists,http%3A%2F%2Ftiny.cc%2Fegu5rx&format=json

This embed query took ~10 seconds

    https://embedkit.com/api/v1/embed?key=s_1234&urls=http%3A%2F%2Fpaper.li%2Fmleiser%2F1295344238,http%3A%2F%2Fbit.ly%2F1APnFq2,http%3A%2F%2Fm.huffpost.com%2Fus%2Fentry%2F6431072,http%3A%2F%2Ftmblr.co%2FZRYINw1aCesA3,http%3A%2F%2Fwww.flightradar24.com%2F48.99%2C2.65%2F11,http%3A%2F%2Fwww.newburytoday.co.uk%2F2015%2Fsmall-milk-leak-from-m4-newburyreading-lorry-tackled-by-firefighters,https%3A%2F%2Ftwitter.com%2Fimbadatlife%2Fstatus%2F553488839747313664,http%3A%2F%2Ftmblr.co%2FZRYINw1aCekCD,http%3A%2F%2FDIYBinge.com,http%3A%2F%2Ftinyurl.com%2Fn649nk5,http%3A%2F%2Ffw.to%2FEuO9b0W&format=json

I'm requesting all the links included in a Twitter timeline - so it's not uncommon to have 10 - 20 URLs.

Requests are coming from the UK.

**Comment by snellingio** [comment]
Thanks a lot to consider here. 

My first thought is - every batch query will take as long as it's slowest URL. What that means to me is that if even one of those URL's takes 10 seconds to fully time out - the whole query will time out. Subsequent requests should all be cached, so no problem for hitting the same URL's over and over.

Second thought is - our datacenter is currently in Dallas, TX. I'll be looking at geo routing requests, or potentially moving our datacenter east coast. 

Just as a side note - I do offer custom endpoint setups closer to your datacenter for enterprises, but I don't think your usage warrants that cost.

Last thought - I may write a new example using curl multi handle so that it chunks requests into two or three URLs. Hopefully this prevents you from have any long running requests.

**Comment by snellingio** [comment]
Another thought - I need to run some dns lookup times to this benchmark as well - I switched dns providers yesterday, and we may be seeing some propagation latency.

**Comment by edent** [comment]
Yeah - I'm not *quite* ready to buy an enterprise grade server ;-)

I could, perhaps, suggest two things.

-  Offer a "simple" service for thumbnails.  For example, it's possible to get thumbs from YouTube, Instagram, Imgur, with a simple regex.

http://img.youtube.com/vi/TDQ6ARJzbOo/hqdefault.jpg (`http://img.youtube.com/vi/{VIDEOID}/hqdefault.jpg`)

http://instagram.com/p/xmOmFkxFnb/media/  (add `/media` to the end of the url)

http://i.imgur.com/igHCfm.jpg (`i.imgur.com/{IMAGEID}m.jpg`)

Sure, it wouldn't get the full information - but but would be quick & would cut down your latency & bandwidth costs.

- Perhaps offer a timeout API option?  At the moment, the CURL timesout after 10 second - but that returns nothing to the program.  Perhaps `&timeout=1000ms` could return whatever EmbedKit has got once the timeout is reached?

Anyway, just some thoughts.  Great service :-)

**Comment by snellingio** [comment]
Both great ideas. I'll be looking at both of those as options going forward. :)  Thanks for all three of those links, the /media finally is making sense to me!
